### ISSUE TITLE
Jobs getting into Processing state multiple times

### ISSUE THREAD

**Issue by kekefigure** [frankhommers/Hangfire.PostgreSql#130]
I'm using Hangfire to process some long running download jobs with PostgreSql storage. Sometimes these jobs gets into processing state twice by the same worker. After the jobs are finished, i get an exception related to business logic, because the download step can run only once. That's correct. The timeline looks like this:

1.  Job1 starts, and enters into Processing state
2. Job1 still running (it can be a couple of hours)
3. Same Job1(call it Job2 from now) enters Processing state again by the same worker
4. Job1 finishes its task successfully, but this doesn't show up in job state (business logic is executed after download is finished)
5. Job2 gets into failed state, because a business exception(starting a download, in downloaded state)

This looks like this in the hangfire db:
![image](https://user-images.githubusercontent.com/9830239/65157204-a8653080-da30-11e9-81e4-1454a7ef36f9.png)

PostgreSqlStorageOptions:
QueuePollInterval = TimeSpan.FromSeconds(10)
InvisibilityTimeout = TimeSpan.FromHours(6)

Versions used:
Hangfire.AspNetCore 1.7.6
Hangfire.PostgreSql 1.6.0

The application is running in two instance, in a kubernetes cluster.

**Comment by kekefigure** [comment]
I investigated our container logs and found the following errors:

**Error on job state change:**
All of the jobs which got HangFire:job:XXX:state-lock exception, got into processing state multiple times.
```
{ 
    {
        "timestamp": "2019-09-21T07:33:06.509379505Z",
        "content": "      10 state change attempt(s) failed due to an exception, moving job to the FailedState"
    }, {
        "timestamp": "2019-09-21T07:33:06.509384081Z",
        "content": "Hangfire.PostgreSql.PostgreSqlDistributedLockException: Could not place a lock on the resource 'HangFire:job:1585:state-lock': Lock timeout."
    }, {
        "timestamp": "2019-09-21T07:33:06.509387733Z",
        "content": "   at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)"
    }, {
        "timestamp": "2019-09-21T07:33:06.509391227Z",
        "content": "   at Hangfire.PostgreSql.PostgreSqlDistributedLock..ctor(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)"
    }, {
        "timestamp": "2019-09-21T07:33:06.509394654Z",
        "content": "   at Hangfire.PostgreSql.PostgreSqlConnection.AcquireDistributedLock(String resource, TimeSpan timeout)"
    }, {
        "timestamp": "2019-09-21T07:33:06.509398123Z",
        "content": "   at Hangfire.Storage.StorageConnectionExtensions.AcquireDistributedJobLock(IStorageConnection connection, String jobId, TimeSpan timeout)"
    }, {
        "timestamp": "2019-09-21T07:33:06.509401489Z",
        "content": "   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)"
    }, {
        "timestamp": "2019-09-21T07:33:06.509404706Z",
        "content": "   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)"
    }, {
        "timestamp": "2019-09-21T07:34:25.874513665Z",
        "content": "\u001b[41m\u001b[30mfail\u001b[39m\u001b[22m\u001b[49m: Hangfire.Server.Worker[0]"
    }
}
```
**Error at fetching jobs:**
```sql
ERROR:  could not serialize access due to concurrent update
STATEMENT:  
	UPDATE "hangfire"."jobqueue" 
	SET "fetchedat" = NOW() AT TIME ZONE 'UTC'
	WHERE "id" IN (
	    SELECT "id" 
	    FROM "hangfire"."jobqueue" 
	    WHERE "queue" = ANY ($1)
	    AND "fetchedat" IS NULL
	    ORDER BY
	    CASE "queue"
	        WHEN 'process_s1' THEN 0
	WHEN 'download_s1' THEN 1
	        ELSE 2
	    END,
	    "fetchedat", "jobid"
	    LIMIT 1
	)
	RETURNING "id" AS "Id", "jobid" AS "JobId", "queue" AS "Queue", "fetchedat" AS "FetchedAt"
```

**Lock errors:**
```sql
ERROR:  duplicate key value violates unique constraint "lock_resource_key"
DETAIL:  Key (resource)=(HangFire:recurring-jobs:lock) already exists.
STATEMENT:  
	INSERT INTO "hangfire"."lock"("resource", "acquired") 
	SELECT $1, $2
	WHERE NOT EXISTS (
	    SELECT 1 FROM "hangfire"."lock" 
	    WHERE "resource" = $1
	)
```

```sql
ERROR:  duplicate key value violates unique constraint "lock_resource_key"
DETAIL:  Key (resource)=(HangFire:locks:schedulepoller) already exists.
STATEMENT:  
	INSERT INTO "hangfire"."lock"("resource", "acquired") 
	SELECT $1, $2
	WHERE NOT EXISTS (
	    SELECT 1 FROM "hangfire"."lock" 
	    WHERE "resource" = $1
	)
```

**Comment by zhiyuanzhang-unai** [comment]
We are getting the same issue.
Job is in processing state multiple times.

Any fix for this?

**Comment by pirimoglu** [comment]
We are getting the same issue and a lot of postgresql errors.

**Comment by kamyker** [comment]
I had small error resulting in exception in recurring job that in ~8 hours eat up a lot of rows from database. Fortunately I'm not using it for anything else so simply could remove everything. I there any way to keep cleaning it up somehow regularly? In one week somehow it ate up almost 10k rows using only 2 jobs.

**Comment by YeAungKyaw20** [comment]
i haves used two npgsqlcommand and geneate mulitple rows . So HangFire Job is mulitple "Processing" state . How can u fix it ? 
![hangfire](https://user-images.githubusercontent.com/58065621/74426261-6e834380-4e83-11ea-9e40-c4cc527caeec.png)

**Comment by xklonx** [comment]
Ive found that PostgreSqlStorageOptions.DistributedLockTimeout defaults to 10 minutes, after that job would be runned again even if you use DisableConcurrentExecutionAttribute because lock is released by  TryRemoveDeadlock.
And i think this issue is connected with #119

**Comment by vytautask** [comment]
We've released 1.6.4.2 version with the potential fix from @davidroth. Please update and check again.

**Comment by Qubitus** [comment]
Just tested it now with version 1.8.0, still experiencing this issue.

**Comment by vytautask** [comment]
That's an old thread, but this is probably fixed with more recent version of 1.5.8.2

**Comment by Frazi1** [comment]
If a job is taking more time to complete than `InvisibilityTimeout` value, then your job will be restarted over and over.

The default value for `InvisibilityTimeout` is `30 minutes`, I think. So, if your job is longer than `30 minutes`, you can try and increase that timeout to a greater value like `1 hour`.
