### ISSUE TITLE
InvalidCastException if used with Hangfire.Console

### ISSUE THREAD

**Issue by totalprogrammi** [frankhommers/Hangfire.PostgreSql#63]
If used with Hangfire.Console, an exception is thrown when scheduling jobs.
Disabling Console, no error is thrown. Console seems to work correctly with other storages (or maybe a similar problem with Mongo).

Exception:

Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> System.InvalidCastException: Unable to cast object of type 'Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.
   at Hangfire.Console.States.ConsoleApplyStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at ... (hidden)"

Packages:
Hangfire 1.6.9
Hangfire.Core 1.6.9
Hangfire.PostgreSql 1.4.6
Hangfire.Console 1.3.0

**Comment by totalprogrammi** [comment]
https://github.com/pieceofsummer/Hangfire.Console/issues/17

**Comment by vytautask** [comment]
Currently looking into it. Will update with solution ;)

**Comment by vytautask** [comment]
Updated packages in NuGet and placed one in GitHub. Thanks for reporting!

**Comment by totalprogrammi** [comment]
Maybe the problem is not resolved.

Please see:
https://github.com/pieceofsummer/Hangfire.Console/issues/17#issuecomment-288041445

**Comment by vytautask** [comment]
I will create some tests and investigate this further.

**Comment by vytautask** [comment]
@totalprogrammi please confirm that the issue is resolved. Thanks!

**Comment by totalprogrammi** [comment]
Seems to work perfectly! Thank You!

**Comment by gornialberto** [comment]
I'm still having the exception:

> System.InvalidCastException

Unable to cast object of type 'Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.

System.InvalidCastException: Unable to cast object of type 'Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.
   at Hangfire.Console.States.ConsoleApplyStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)

>
